### ISSUE TITLE
Provider matches that has status=off are appearing in Match Mapping page

### ISSUE THREAD

**Issue by BrianRuchiadi** [fifasports/Test-Round-1#2]
Why most of the matches at the moment in UAT match mapping are off matches?
They still can be officialized, but they are off.

![image](https://user-images.githubusercontent.com/373000/114418492-237ad280-9be5-11eb-9266-89937c5dabb8.png)

**Comment by coder77** [comment]
From Samuel:

Got few scenario when officialize match:

1. Match went offline=1 if all it's primary provider's match status are Off
2. Match went publish=0 if match setting set so OR no provider odds found OR score & events not found for live match (soccer)
3. After match is officialized, it might went off after few seconds if match.start_time is past NOW and status still prematch. There is a running script in PS that does this process

**Comment by BrianRuchiadi** [comment]
Seems like betradar puller didnt send match off, so, it is appearing past its time
