### ISSUE TITLE
Some Betradar matches that does not sending odds

### ISSUE THREAD

**Issue by BrianRuchiadi** [fifasports/Test-Round-1#5]
There are some Betradar matches that does not sending odds. 
It is causing after match that officialized, does not have official odds.

**Comment by BrianRuchiadi** [comment]
I think this is due to betradar ZMQ issue. After restarting betradar, working perfectly fine

**Comment by coder77** [comment]
ZMQ issue is one of side effect of the root problem, it is most probably coming from high CPU/Memory that causing it.
But yes, this issue should be close.
