### ISSUE TITLE
Non soccer matches did not showing up in odds page after officialized

### ISSUE THREAD

**Issue by BrianRuchiadi** [fifasports/Test-Round-1#6]
![image](https://user-images.githubusercontent.com/14333265/114432012-5e333980-9bea-11eb-8591-a635a15cfa2e.png)
![image](https://user-images.githubusercontent.com/14333265/114432076-7b680800-9bea-11eb-98d2-7579568157ee.png)
![image](https://user-images.githubusercontent.com/14333265/114432113-8884f700-9bea-11eb-95bd-1eb79e42e2ea.png)

**Comment by safi7** [comment]
soccer, basketball, baseball, ice hockey, handball, volleyball, cricket, tennis, table tennis, badminton all can display.
some matches which dont display might because they are off.
![image](https://user-images.githubusercontent.com/42130564/114486178-ec85da80-9c3f-11eb-88cd-95a9de65423f.png)

**Comment by BrianRuchiadi** [comment]
Verified, Safi.
It was due to ZMQ issue on betradar puller part.
working perfectly
:)
