### ISSUE TITLE
CMS (hot-keywords) response is null

### ISSUE THREAD

**Issue by jiahao9999** [fifasports/Test-Round-1#8]
![image](https://user-images.githubusercontent.com/48431098/114485486-906e8680-9c3e-11eb-9a06-0c2314d0b705.png)

`https://testpp.ug88.net/service/player/hotKeywords`
response is null . which shouldn't be 

maybe because they didn't sync to `http://{{host_feed_internal}}/{{version}}/cms/search-keywords`
which should have records 
![image](https://user-images.githubusercontent.com/48431098/114485600-c875c980-9c3e-11eb-8205-33d7c38cfbb0.png)

**Comment by jiahao9999** [comment]
![image](https://user-images.githubusercontent.com/48431098/114519114-a72ed080-9c72-11eb-9b2a-675f3a926772.png)
CMS (messages) created a new message also not reflected to player portal 

maybe because they didn't sync to `http://{{host_feed_internal}}/{{version}}/messages?page=1&per_page=1000`
which should have records
![Uploading image.png…]()

**Comment by coder77** [comment]
Our side should be alright, but could not reflect in NT portal
